### ISSUE TITLE
SE-URLを踏むと落ちることがある？

### ISSUE THREAD

**Issue by laco0416** [laco0416/SmileEssence#68]
4 分前
1.0.8
Xperia UL（SOL22）
やはりリンク(画像)を開くと落ちる 時系列で書くと、 リンクを押す→ アプリ落ちる→ 画像がブラウザーで表示(落ちるのとほぼ同時だがやや後) あひる
24 分前
1.0.8
Xperia UL（SOL22）
URLを踏んだ瞬間クラッシュ ただ、頻度としてはかなり稀 あひる
6月14日 23:39
1.0.3
Photon 4G（sunfire）
端末 MOTOROLA photon Android 4.4.2 SEs 1.0.3 ツイートの画像URLをタップしてインテントメニューを出して画像を開くアプリを連打すると再起動します。標準ブラウザ、twicca、OrangeSphereで確認しました。

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1322)
at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1333)
at android.app.BackStackRecord.commitInternal(BackStackRecord.java:595)
at android.app.BackStackRecord.commit(BackStackRecord.java:574)
at net.lacolaco.smileessence.view.dialog.DialogHelper.close(DialogHelper.java:98)
at net.lacolaco.smileessence.view.dialog.DialogHelper.showDialog(DialogHelper.java:79)
at net.lacolaco.smileessence.viewmodel.StatusViewModel.onClick(StatusViewModel.java:487)
at net.lacolaco.smileessence.viewmodel.StatusViewModel.access$100(StatusViewModel.java:58)
at net.lacolaco.smileessence.viewmodel.StatusViewModel$2.run(StatusViewModel.java:402)
at net.lacolaco.smileessence.view.listener.ListItemClickListener$1.run(ListItemClickListener.java:67)
at android.os.Handler.handleCallback(Handler.java:725)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:5092)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by laco0416** [comment]
4月23日 22:37
1.0.11.1
Xperia Z3（SOL26）
リンク踏んだら落ちた 再現方法確立できてない

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1327)
at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1345)
at android.app.BackStackRecord.commitInternal(BackStackRecord.java:597)
at android.app.BackStackRecord.commit(BackStackRecord.java:575)
at net.lacolaco.smileessence.view.dialog.DialogHelper.close(DialogHelper.java:98)
at net.lacolaco.smileessence.view.dialog.DialogHelper.showDialog(DialogHelper.java:79)
at net.lacolaco.smileessence.viewmodel.StatusViewModel.onClick(StatusViewModel.java:487)
at net.lacolaco.smileessence.viewmodel.StatusViewModel.access$100(StatusViewModel.java:58)
at net.lacolaco.smileessence.viewmodel.StatusViewModel$2.run(StatusViewModel.java:402)
at net.lacolaco.smileessence.view.listener.ListItemClickListener$1.run(ListItemClickListener.java:67)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:212)
at android.app.ActivityThread.main(ActivityThread.java:5137)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
at dalvik.system.NativeStart.main(Native Method)
```
